[package]
name = "freedom-ipfs-retrieval"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
cid.workspace = true
freedom-ipfs-core.workspace = true
freedom-ipfs-namesys.workspace = true
freedom-ipfs-routing.workspace = true
freedom-ipfs-store.workspace = true
futures.workspace = true
libp2p.workspace = true
libp2p-stream.workspace = true
prost.workspace = true
reqwest.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
unsigned-varint.workspace = true
url.workspace = true
