[package]
name = "freedom-ipfs-namesys"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
async-trait.workspace = true
cid.workspace = true
futures.workspace = true
ipld-core = "0.4"
libp2p-identity.workspace = true
multihash.workspace = true
prost.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_ipld_dagcbor.workspace = true
thiserror.workspace = true
time.workspace = true
tracing.workspace = true

[dev-dependencies]
tokio.workspace = true
