[package]
name = "freedom-ipfs-routing"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
cid.workspace = true
async-trait.workspace = true
freedom-ipfs-namesys.workspace = true
futures.workspace = true
libp2p.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
url.workspace = true
